### ISSUE TITLE
`ksync get` should provide info regarding both Pod and Container.

### ISSUE THREAD

**Issue by ashahba** [vapor-ware/ksync#155]
I'm using a multi-container Pod as described here: https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/ and I have modified it so the containers don't exit as below:
```
apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ['-c', 'while true; do echo Hello from the debian container > /pod-data/index.html; sleep 10; done']
```
Once I deployed the Pod, I labeled it as follows:
```
kubectl label pod two-containers app=two-containers
```
and finally I call `ksync create` twice like this:
```
$ ksync create -c nginx-container --selector=app=two-containers /Users/ashahba/jpgs/ /jpgs
$ ksync create -c debian-container --selector=app=two-containers /Users/ashahba/jpgs/ /jpgs
```
but when I call `ksync get` I have:
```
$ ksync get
      NAME               LOCAL              REMOTE       STATUS         POD        
+---------------+----------------------+--------------+----------+----------------+
  busy-parakeet   ../../../jpgs-debian   /jpgs-debian             
                                                        watching   two-containers  
  warm-lemming    ../../../jpgs-nginx    /jpgs-nginx              
                                                        watching   two-containers  
```

As you see there is no way for me to tell with Container is used to Sync with folder(s).
Even when I check the UI, it only shows the one Pod under remote devices.
![screen shot 2018-05-03 at 11 22 13 am](https://user-images.githubusercontent.com/12436063/39595409-4802f48c-4ec4-11e8-9584-b4265b3a331e.png)

For this reason I believe `ksync get` should provide `Container` name within the Pod as well for unique identification of Synced folders.
