### ISSUE TITLE
Context should be attached to spec

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/ksync#206]
Right now, global context is taken from:
1. Overrides (env vars, flags, etc.)
2. Ksync config file
3. Configured `kubectl` context

In ascending order. We should separate out global context from context for individual specs so that:

- A spec is attached to a context (and only checks that context)
- Multiple contexts can be checked
- Changing contexts does not change specs/global context when not intended

Something like this in `ksync.yaml`
```yaml
apikey: ksync
 context: cluster-awesome
 log-level: debug
 namespace: default
 output: pretty
 port: 40322
 spec:
 - name: loving-akita
   context: cluster-super
   containername: ""
   pod: ""
   selector: app=test
   namespace: default
   localpath: /tmp/code
   remotepath: /tmp
   reload: true
   localreadonly: false
   remotereadonly: false
 syncthing-port: 8384
```

Related to #167
