### ISSUE TITLE
Doesn't sync with mounted emptyDir Pod volumes 

### ISSUE THREAD

**Issue by cheddarwhizzy** [vapor-ware/ksync#230]
If I try to sync to a pod path using emptyDir as the volume, data is synced to the `/var/lib/docker/overlay2/ID/merged/usr/share/nginx/html` directory, but not synced to the `/var/lib/kubelet/pods/6df2b982-b524-11e8-b615-382c4ac7fe86/volumes/kubernetes.io~empty-dir/test` and therefore not inside the running pod. 

Here are the 2 examples:

Will NOT work (using emptyDir volume as sync dir)
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: test-copy
  name: test-copy
spec:
  selector:
    matchLabels:
      run: test-copy
  template:
    metadata:
      labels:
        run: test-copy
    spec:
      containers:
      - image: nginx
        name: test-copy
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test
      volumes:
      - emptyDir: {}
        name: test
```
```
ksync create --log-level=debug --name nginx-test --namespace=default --reload=false -l run=test-copy `pwd` /usr/share/nginx/html/
```

Will sync
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: test-copy2
  name: test-copy2
  namespace: default
spec:
  selector:
    matchLabels:
      run: test-copy2
  template:
    metadata:
      labels:
        run: test-copy2
    spec:
      containers:
      - image: nginx
        name: test-copy2
```
```
ksync create --log-level=debug --name nginx-test2 --namespace=default --reload=false -l run=test-copy2 `pwd` /usr/share/nginx/html/
```
