### ISSUE TITLE
file not sync

### ISSUE THREAD

**Issue by fkpwolf** [vapor-ware/ksync#252]
I tested with ksync/example/app following "Getting Started". But local folder didn't get sync and was empty. I try to add some files to local and can't sync them to example pod.

In console of syncthing container, `ls /var/lib/docker/overlay2/69336c3194f0230d0610c76b42a9b5fa49ab0dccf21b416c
57aa1ba9527d311d/merged/code/` can list files which has synced with my local folder. But the path in example pod still return original list.

Looks local files get synced but sync to a wrong place.

**Comment by timfallmk** [comment]
@fkpwolf Could you paste your sync paths? If you paste `~/.ksync/config` that should contain everything.

**Comment by fkpwolf** [comment]
There is only `.ksync/ksync.yaml`, no config file.
```yaml
apikey: ksync
context: ""
docker-root: /var/lib/docker
log-level: info
namespace: default
output: pretty
port: 40322
spec:
- name: noble-rattler
  containername: ""
  pod: ""
  selector:
  - app=app
  namespace: default
  localpath: /home/centos/ksync
  remotepath: /code
  reload: true
  localreadonly: false
  remotereadonly: false
syncthing-port: 8384
```
The localpath value is correct.
