### ISSUE TITLE
Kubernetes API Access Required by Ksync

### ISSUE THREAD

**Issue by alok87** [vapor-ware/ksync#287]
Use Case: There is a single kubernetes cluster shared by many developers. Every developer has a namespace in the cluster.

~What all accesses is required to have for kubectl in localhost to use ksync for a single namespace?~ 

What is the access required by `ksync watch` to talk to Kubernetes API?
Which all objects does ksync watch will query for kubernetes API?

Please suggest.

**Comment by timfallmk** [comment]
Strictly speaking you don't *need* `kubectl` to use `ksync`. You do need a context that is capable of reaching the cluster. We don't do any RBAC within `ksync` itself, that's all delegated to the connection and uses the normal context-based method. And segmentation you do within your cluster should be respected in `ksync`

**Comment by alok87** [comment]
I meant access ksync will make calls to kubernetes api server. What all accesses ksync needs to talk to k8s api server. We have a single k8s cluster. We do not want to open up admin k8s api access for every user of the cluster. We want to give the exact acceses it needs.

**Comment by alok87** [comment]
Based on https://github.com/vapor-ware/ksync/blob/master/pkg/ksync/spec.go#L109
The machine in which ksync runs should have access for below role to access k8s api 
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {user-specfied}
  name: pod-watcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
```
Correct?
Or there is anything more.

My aim is to find the exact access i need to open up for k8s api in the developer machine to access Kubernetes API. So that ksync starts working with only the permissions it needs and not more than that.
